---
title: HelmuthB
timezone: Europe/Vienna
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: me@helmuth.at
description: Full Stack Developer
baseurl: 
url: https://helmuth.at
twitter_username: helmuthb
github_username: helmuthb
markdown: kramdown
