---
title: Helmuth @
timezone: Europe/Vienna
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: me@helmuth.at
description: Software Developer
baseurl: 
url: https://helmuth.at
twitter_username: helmuthb
github_username: helmuthb
markdown: kramdown
sass:
  style: compressed
jekyll-minifier:
  compress_css: false
extlinks:
  attributes: {rel: nofollow, target: _blank}
gems:
- jekyll-minifier
- jekyll-extlinks
